version: '3.8'
services:
  exprisma:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: prisma
    networks:
      - santiago
networks:
  santiago: